### PR TITLE
Add tests showing preceding-blankline bug

### PR DESCRIPTION
**Pull request by bskinn**
Adding failing test cases per request in #20.

### CODE REVIEW

**Comment by ar4s** [comment]
@bskinn Thank you for this PR and issue. I going to fix this in the next few days.

**Comment by bskinn** [comment]
Sure thing! Thanks for writing & publishing the plugin.

**Comment by ar4s** [comment]
@bskinn a new version (0.3.1) is uploaded to PyPI.

**Comment by bskinn** [comment]
Cool! Thanks v much for the fix.

**Pull request merged**
